//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoManagementWPF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PianoManagementEntities : DbContext
    {
        public PianoManagementEntities()
            : base("name=PianoManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accord> Accord { get; set; }
        public virtual DbSet<Accordeur> Accordeur { get; set; }
        public virtual DbSet<Entreprise> Entreprise { get; set; }
        public virtual DbSet<Piano> Piano { get; set; }
        public virtual DbSet<Professeur> Professeur { get; set; }
        public virtual DbSet<Salle> Salle { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<Utiliser> Utiliser { get; set; }
    }
}
