//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PianoManagementWPF.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accord
    {
        public int AccordId { get; set; }
        public System.DateTime AccordDate { get; set; }
        public string AccordRemarque { get; set; }
        public int PianoId { get; set; }
        public int AccordeurId { get; set; }
    
        public virtual Accordeur Accordeur { get; set; }
        public virtual Piano Piano { get; set; }
    }
}
